#!/usr/bin/env bash
set -euo pipefail

# LobbyForge one-command installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/lobbyforge/lobbyforge/main/install.sh | bash
#
# Or clone + run locally:
#   git clone https://github.com/lobbyforge/lobbyforge.git
#   cd lobbyforge && bash install.sh
#
# This script:
#   1. Checks prerequisites (Docker, Docker Compose, curl, openssl).
#   2. Prompts for domain name and generates secrets.
#   3. Provisions a Let's Encrypt certificate via certbot.
#   4. Starts the full production stack via docker-compose.prod.yml.
#   5. Runs the Doctor health check.

set -e
umask 077  # Secrets written by this script should only be readable by the owner.

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║     LobbyForge Installer                  ║${NC}"
echo -e "${BOLD}║     Self-hosted voice community platform   ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Prerequisites ──────────────────────────────────────────────
echo -e "${BOLD}Checking prerequisites...${NC}"

check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${RED}✗ $1 is not installed. Please install it first.${NC}"
    echo "   $2"
    exit 1
  fi
}

check_cmd docker "Install Docker: https://docs.docker.com/engine/install/"
check_cmd docker "Install Docker Compose (included with Docker Desktop or 'docker-compose-plugin')"
check_cmd curl "Install curl (usually preinstalled)"
check_cmd openssl "Install openssl (usually preinstalled)"

# Verify docker compose subcommand
if ! docker compose version &>/dev/null; then
  echo -e "${RED}✗ 'docker compose' plugin is not available. Install docker-compose-plugin.${NC}"
  exit 1
fi

echo -e "${GREEN}✓ All prerequisites found.${NC}"
echo ""

# ── 2. Configuration ──────────────────────────────────────────────
echo -e "${BOLD}Configuration${NC}"
echo ""

# Find the repo root (where this script lives or CWD).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/infra/docker/docker-compose.prod.yml"
ENV_FILE="$SCRIPT_DIR/.env.prod"

if [ ! -f "$COMPOSE_FILE" ]; then
  echo -e "${RED}✗ docker-compose.prod.yml not found at $COMPOSE_FILE${NC}"
  echo "   Make sure you're running this from the repo root."
  exit 1
fi

# Domain (validated — used in sed and nginx config)
read -rp "$(echo -e ${BOLD}'Enter your domain (e.g. lobby.example.com): '${NC})" DOMAIN
if [ -z "$DOMAIN" ]; then
  echo -e "${RED}✗ Domain is required for HTTPS/WebRTC.${NC}"
  exit 1
fi
# LF-010: Reject domains that would break sed/nginx config (/, &, \, spaces).
if ! [[ "$DOMAIN" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]*[a-zA-Z0-9]$ ]]; then
  echo -e "${RED}✗ Invalid domain "$DOMAIN" — only letters, digits, dots, and hyphens allowed.${NC}"
  exit 1
fi

# Instance name
read -rp "$(echo -e ${BOLD}'Community name [LobbyForge Community]: '${NC})" INSTANCE_NAME
INSTANCE_NAME="${INSTANCE_NAME:-LobbyForge Community}"

# Deployment mode
read -rp "$(echo -e ${BOLD}'Official hub instance? (enables discovery/marketplace) [y/N]: '${NC})" IS_OFFICIAL
if [[ "$IS_OFFICIAL" =~ ^[Yy]$ ]]; then
  DEPLOYMENT_MODE="official"
else
  DEPLOYMENT_MODE="self_host"
fi

# Generate secrets
echo ""
echo -e "${BOLD}Generating secure secrets...${NC}"
SESSION_SECRET=$(openssl rand -hex 32)
ADMIN_TOKEN=$(openssl rand -hex 32)
SETUP_TOKEN=$(openssl rand -hex 32)
PG_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
LK_API_KEY="devkey_$(openssl rand -hex 8)"
LK_API_SECRET=$(openssl rand -hex 32)

echo -e "${GREEN}✓ Secrets generated.${NC}"
echo ""

# ── 3. Write .env.prod ────────────────────────────────────────────
echo -e "${BOLD}Writing .env.prod...${NC}"

cat > "$ENV_FILE" << EOF
# LobbyForge production environment — generated by install.sh
# Domain: $DOMAIN

# PostgreSQL
POSTGRES_DB=lobbyforge
POSTGRES_USER=lobbyforge
POSTGRES_PASSWORD=$PG_PASSWORD
DATABASE_URL=postgres://lobbyforge:$PG_PASSWORD@postgres:5432/lobbyforge

# Redis
REDIS_PASSWORD=$REDIS_PASSWORD

# LiveKit
LIVEKIT_API_KEY=$LK_API_KEY
LIVEKIT_API_SECRET=$LK_API_SECRET
LIVEKIT_URL=http://livekit:7880
NEXT_PUBLIC_LIVEKIT_URL=wss://$DOMAIN/livekit
NEXT_PUBLIC_WS_URL=wss://$DOMAIN/ws

# Security
LOBBYFORGE_SESSION_SECRET=$SESSION_SECRET
LOBBYFORGE_ADMIN_TOKEN=$ADMIN_TOKEN
LOBBYFORGE_SETUP_TOKEN=$SETUP_TOKEN

# Product
LOBBYFORGE_DEPLOYMENT_MODE=$DEPLOYMENT_MODE
LOBBYFORGE_INSTANCE_NAME=$INSTANCE_NAME
LOBBYFORGE_TRUSTED_PROXY=x-forwarded-for
NEXT_PUBLIC_BASE_URL=https://$DOMAIN

# Node
NODE_ENV=production
EOF

echo -e "${GREEN}✓ .env.prod written. Save these credentials:${NC}"
echo "   Admin token:     $ADMIN_TOKEN"
echo "   Setup token:     $SETUP_TOKEN (remove after first-run setup)"
echo ""

# ── 4. Configure nginx domain ─────────────────────────────────────
echo -e "${BOLD}Configuring Nginx for $DOMAIN...${NC}"
NGINX_CONF="$SCRIPT_DIR/infra/nginx/conf.d/app.conf"
if [ -f "$NGINX_CONF" ]; then
  sed -i.bak "s/LOBBYFORGE_DOMAIN/$DOMAIN/g" "$NGINX_CONF"
  echo -e "${GREEN}✓ Nginx configured.${NC}"
fi

LIVEKIT_CONF="$SCRIPT_DIR/infra/livekit/livekit.yaml"
if [ -f "$LIVEKIT_CONF" ]; then
  sed -i.bak "s/LOBBYFORGE_DOMAIN/$DOMAIN/g" "$LIVEKIT_CONF"
  echo -e "${GREEN}✓ LiveKit configured.${NC}"
fi
echo ""

# ── 5. Provision SSL certificate ──────────────────────────────────
echo -e "${BOLD}Provisioning SSL certificate via Let's Encrypt...${NC}"
echo -e "${YELLOW}This requires port 80 to be open and DNS to point here.${NC}"
read -rp "$(echo -e ${BOLD}'Proceed with certbot now? [Y/n]: '${NC})" DO_CERTBOT
DO_CERTBOT="${DO_CERTBOT:-Y}"

# LF-010: Initialize explicitly to avoid unbound variable with set -u.
CERT_FAILED=false

if [[ "$DO_CERTBOT" =~ ^[Yy]$ ]]; then
  # LF-010: Use --standalone mode — certbot runs its own HTTP server on
  # port 80 for the challenge (requires port 80 free; the full stack
  # starts AFTER this succeeds). This is simpler and more reliable than
  # webroot mode which would need a running nginx serving the challenge dir.
  if docker run --rm \
    -p 80:80 \
    -v "$SCRIPT_DIR/infra/certbot/conf:/etc/letsencrypt" \
    certbot/certbot certonly --standalone \
    -d "$DOMAIN" \
    --non-interactive \
    --agree-tos \
    --register-unsafely-without-email \
    --no-eff-email; then
    if [ -d "$SCRIPT_DIR/infra/certbot/conf/live/$DOMAIN" ]; then
      echo -e "${GREEN}✓ Certificate provisioned for $DOMAIN${NC}"
    else
      echo -e "${RED}✗ Certificate directory not found — certbot may have failed silently.${NC}"
      CERT_FAILED=true
    fi
  else
    echo -e "${RED}✗ Certbot FAILED.${NC}"
    echo "   Common causes: DNS not pointing here yet, port 80 blocked, rate limit."
    CERT_FAILED=true
  fi
else
  echo -e "${YELLOW}Skipping certbot.${NC}"
  CERT_FAILED=true
fi

# P0-D: Fail-closed — WebRTC requires HTTPS (secure context). Without a
# certificate the production Nginx config cannot start (it loads cert files
# unconditionally), so aborting is the only safe action.
if [ "$CERT_FAILED" = true ]; then
  echo ""
  echo -e "${RED}✗ TLS certificate is not available. Aborting — WebRTC voice requires HTTPS.${NC}"
  echo "   Fix the issue above and re-run: bash install.sh"
  exit 1
fi
echo ""

# ── 6. Start the stack ────────────────────────────────────────────
echo -e "${BOLD}Starting LobbyForge...${NC}"
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build

echo ""
echo -e "${GREEN}${BOLD}✓ LobbyForge is starting!${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Visit https://$DOMAIN to run the first-run setup wizard."
echo "  2. Use the Setup Token when prompted: $SETUP_TOKEN"
echo "  3. After setup, remove the Setup Token from .env.prod."
echo "  4. Visit Admin → Doctor & Health to verify everything is healthy."
echo ""
echo -e "${BOLD}Important credentials (save these!):${NC}"
echo "  Admin Token:  $ADMIN_TOKEN"
echo "  Setup Token:  $SETUP_TOKEN (remove after setup!)"
echo ""
echo -e "${BOLD}To stop:${NC}  docker compose -f $COMPOSE_FILE --env-file $ENV_FILE down"
echo -e "${BOLD}To update:${NC}  docker compose -f $COMPOSE_FILE --env-file $ENV_FILE pull && docker compose -f $COMPOSE_FILE --env-file $ENV_FILE up -d --build"
