// Generated by `pnpm i18n:sync` from ../locales/*.json — do not edit.
// Add a language with `pnpm i18n:add <code>`; see docs/TRANSLATING.md.
import en from '../locales/en.json';
import tr from '../locales/tr.json';

/** Every language this plugin ships, English first. */
export const LOCALE_TABLES = {
  en,
  tr,
};

export const SHIPPED_LOCALES: string[] = Object.keys(LOCALE_TABLES);
