-- 18th-audit: persist the directory verification proof so the
-- .well-known endpoint can serve it without manual Redis writes.
-- The proof is Ed25519(privateKey, canonical payload) — generated by
-- lfctl directory proof, stored here by the admin configure endpoint.
ALTER TABLE "instance_settings" ADD COLUMN "directory_proof" text;
