-- security-review HUB-001: a directory identity that is unique per
-- instance. The settings singleton is keyed `instance_id = 'self-host'` on
-- EVERY install, so publishing that key as the directory id would let the
-- first hub account to register `self-host` own the entry for everybody.
-- Each install gets its own random id instead (UUID v4, generated by
-- Postgres; a volatile default is evaluated per existing row, so installs
-- upgraded through this migration get distinct ids too). Additive (expand
-- only) — the previous image ignores the column, so app rollback is safe.
ALTER TABLE "instance_settings" ADD COLUMN IF NOT EXISTS "directory_instance_id" text DEFAULT gen_random_uuid()::text NOT NULL;
